version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WIDE_COLUMN_DB_HOST: cassandra
      WIDE_COLUMN_DB_KEYSPACE: bdnr
      WIDE_COLUMN_DB_LOCAL_DATA_CENTER: datacenter1
      WIDE_COLUMN_DB_NAME: vehicle_registry
      PORT: 80
    depends_on:
      - cassandra
    ports:
      - "3000:80"
    volumes:
      - ./app/src:/app/src
      - ./app/node_modules:/app/node_modules

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - cassandra-volume:/var/lib/cassandra
    restart: always

volumes:
  cassandra-volume:
